backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('reports.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

backend/reports/urls.py
from django.urls import path

from . import views

app_name = 'reports'

urlpatterns = [
    path('', views.index, name='index'),
    path('report/send/', views.upload_file, name='send'),
    path('report/edit/<int:pk>', views.edit_file, name='edit'),
    path('report/delete/<int:pk>', views.delete_file, name='delete'),
    path('data/uploads_reports/<int:pk>', views.get_file, name='get_file'),
    path('data/reports/<int:pk>', views.get_report, name='get_report'),
]

backend/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

backend/reports/models.py
import os

from django.contrib.auth import get_user_model
from django.db import models

from backend.settings import MEDIA_ROOT

from .validators import validate_py_file

User = get_user_model()


class File(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='files',
        verbose_name='пользователь'
    )
    file = models.FileField(
        upload_to='uploads_reports/',
        validators=(validate_py_file,)
    )
    created_at = models.DateTimeField(auto_now=True)
    is_reported = models.BooleanField(default=False)
    is_checked = models.BooleanField(default=False)
    is_reloaded = models.BooleanField(default=False)

    @property
    def filename(self):
        return os.path.basename(self.file.name)


class Report(models.Model):
    file = models.OneToOneField(
        File,
        on_delete=models.CASCADE,
        related_name='report',
        verbose_name='файл'
    )
    report_file = models.FileField(upload_to='reports/', null=True)

    @property
    def filename(self):
        return os.path.basename(self.report_file.path)

    @property
    def report_path(self):
        path = MEDIA_ROOT / 'reports'
        path.mkdir(exist_ok=True)
        return path


class Pep8Warning(models.Model):
    report = models.ForeignKey(
        Report,
        on_delete=models.CASCADE,
        related_name='pep8_warnings',
        verbose_name='отчёт по pep8'
    )
    status_code = models.CharField(max_length=5, verbose_name='код статуса')
    line = models.IntegerField(verbose_name='строка')
    column = models.IntegerField(verbose_name='столбец')
    message = models.CharField(max_length=255, verbose_name='сообщение')
    code_line = models.CharField(max_length=510, verbose_name='строка кода')

    def __str__(self):
        return f'{self.status_code} col:{self.column} [{self.message}]'

backend/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from .managers import CustomUserManager


class User(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

backend/reports/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import File

User = get_user_model()


class UploadFileForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all(), required=False)

    class Meta:
        model = File
        fields = ('file', 'user')

backend/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email',)

backend/core/views.py
from http import HTTPStatus

from django.shortcuts import render


def page_not_found(request, exception):
    return render(
        request,
        'core/404.html',
        {'path': request.path},
        status=HTTPStatus.NOT_FOUND
    )


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')


def server_error(requests):
    return render(
        requests, 'core/500.html', status=HTTPStatus.INTERNAL_SERVER_ERROR
    )


def permission_denied(requests, exception):
    return render(requests, 'core/403.html', status=HTTPStatus.FORBIDDEN)

backend/reports/views.py
from http import HTTPStatus

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import FileResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from backend.settings import ITEMS_ON_PAGE

from .forms import UploadFileForm
from .models import File
from .permissions import check_is_owner


@login_required
def index(request):
    files_list = File.objects.filter(
        user=request.user
    ).select_related('user').prefetch_related('report').order_by('-created_at')
    paginator = Paginator(files_list, ITEMS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'report/index.html', context)


def upload_file(request):
    form = UploadFileForm(request.POST, files=request.FILES)
    if form.is_valid():
        file = form.save(commit=False)
        file.user = request.user
        file.save()
        return HttpResponseRedirect('/', HTTPStatus.NO_CONTENT)
    for error in form.errors.values():
        messages.error(request, error[0])
    return HttpResponseRedirect('/', HTTPStatus.INTERNAL_SERVER_ERROR)


@login_required
@check_is_owner
def delete_file(request, pk):
    file = get_object_or_404(File, pk=pk)
    file.delete()
    return HttpResponseRedirect('/', HTTPStatus.NO_CONTENT)


@login_required
@check_is_owner
def edit_file(request, pk):
    file = get_object_or_404(File, pk=pk)
    form = UploadFileForm(request.POST, files=request.FILES)
    if form.is_valid():
        new_file = form.cleaned_data['file']
        file.file = new_file
        file.is_reloaded = True
        file.is_reported = False
        file.is_checked = False
        file.save()
        return HttpResponseRedirect('/', HTTPStatus.NO_CONTENT)
    for error in form.errors.values():
        messages.error(request, error[0])
    return HttpResponseRedirect('/', HTTPStatus.INTERNAL_SERVER_ERROR)


@login_required
@check_is_owner
def get_file(request, pk):
    file = get_object_or_404(File, pk=pk)
    return FileResponse(file.file, 'rb')


@login_required
@check_is_owner
def get_report(request, pk):
    file = get_object_or_404(File, pk=pk)
    report = file.report
    return FileResponse(report.report_file, 'rb')

backend/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('reports:index')
    template_name = 'users/signup.html'

backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/logo.ico' %}" type="image">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        {{ title }}
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        нет информации
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

backend/templates/core/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка 403{% endblock %}
{% block content %}
  <h1>Ошибка 403</h1>
  <p>Ошибка csrf токена</p>
  <a href="{% url 'reports:index' %}">перейти на главную страницу</a>
{% endblock %} 

backend/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
  <div class="footer-copyright text-center py-3">
    <p><span style="color:darkorange">PEP8</span>Checker</p>
  </div>
</footer>

backend/templates/includes/header.html
{% load static %}
{% with view_name=request.resolver_match.view_name %}
<header>
  <nav class="navbar navbar-light" style="background-color: deepskyblue">
    <div class="container">
      <a class="navbar-brand d-flex align-items-center" href="{% url 'reports:index' %}">
        <img src="{% static 'img/logo.png' %}"
             width="45"
             height="45"
             class="d-inline-block align-top"
             alt="">
        <h2 class="ml-2 mb-0"><span style="color:orange">PEP8</span><span style="color:darkorange">Checker</span></h2>
      </a>
      <ul class="nav nav-pills ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link link-light
               {% if view_name  == 'users:logout' %}active{% endif %}"
               href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li class="nav-item">
            <p>Пользователь: {{ user.email }}</p>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light
               {% if view_name  == 'users:login' %}active{% endif %}"
               href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light
               {% if view_name  == 'users:signup' %}active{% endif %}"
               href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>
{% endwith %}

backend/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

backend/templates/report/index.html
{% extends "base.html" %}
{% block title %}главная страница{% endblock %}
{% block content %}
    {% for message in messages %}
    <div class="alert alert-dismissible {% if message.tags == 'success' %}alert-success{% elif message.tags == 'error' %}alert-danger{% elif message.tags == 'warning' %}alert-warning{% else %}alert-info{% endif %}">
        <strong>{{ message|striptags }}</strong>
    </div>
{% endfor %}
    <div class="container">
        <h1>Загрузка файла</h1>
        {% if message %}
            <div class="alert alert-info">
                {{ message }}
            </div>
        {% endif %}
        <form method="post" action="{% url 'reports:send' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="fileInput">Выберите файл:</label>
                <input type="file" class="form-control-file" id="fileInput" name="file">
            </div>
            <button type="submit" class="btn btn-primary">Загрузить</button>
        </form>
        <hr>
        <h2>Список загруженных файлов:</h2>
        {% for file in page_obj %}
            <div class="card my-2">
                <div class="card-body">
                    <h2><a href="{% url 'reports:get_file' file.pk %}">{{ file.filename }}</a></h2>
                    {% if file.is_checked %}
                        <p>Отчёт: <a href="{% url 'reports:get_report' file.pk %}">{{ file.report.filename }}</a></p>
                    {% endif %}
                    <p>Статус:
                        {% if file.is_reported %}
                            Отчёт отправлен на почту
                        {% elif file.is_checked %}
                            Проверен
                        {% elif file.is_reloaded %}
                            Обновлён
                        {% else %}
                            Новый
                        {% endif %}
                    </p>
                    <form method="POST" action="{% url 'reports:delete' file.id %}">
                        {% csrf_token %}
                        <button class="btn btn-danger" type="submit">Удалить</button>
                    </form>
                    <form method="post" action="{% url 'reports:edit' file.id %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="fileInput">Выберите файл для замены:</label>
                            <input type="file" class="form-control-file" id="fileInput" name="file">
                        </div>
                        <button type="submit" class="btn btn-secondary">заменить</button>
                    </form>
                </div>
            </div>
        {% empty %}
            <p>Нет загруженных файлов</p>
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

backend/templates/report/report_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

backend/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

backend/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}>
          {% csrf_token %}
          {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}